export enum ParserIssueCode {
    None = 'none',
    Unspecified = 'unspecified',
    MandatoryEpdMissing = 'mandatoryEpdMissing',
    InvalidDate = 'invalidDate',
    StringTooShort = 'stringTooShort',
    WrongStartingCharacters = 'wrongStartingCharacters',
    InvalidSeparationBetweenElements = 'invalidSeparationBetweenElements',
    UnsupportedVersion = 'unsupportedVersion',
    IncompleteCode = 'incompleteCode',
    EmptyElementContent = 'emptyElementContent',
    InvalidElementLength = 'invalidElementLength',
    TooLongElement = 'tooLongElement',
    NonEmptyElementContent = 'nonEmptyElementContent',
    InvalidCharsetInElement = 'invalidCharsetInElement',
    TooManyAltPmtFields = 'tooManyAltPmtFields',
    CannotContainSpaces = 'cannotContainSpaces',
}